services:
    smarty.name_parser:
        class: Symfony\Component\Templating\TemplateNameParser
        arguments: ['@kernel']

    smarty.filesystem_loader:
        class: Symfony\Component\Templating\Loader\FilesystemLoader
        arguments: ['%smarty.default_path%']

    smarty.extension.routing:
        autowire: true
        class: Vierwd\Symfony\Smarty\Extension\RoutingExtension

    smarty.extension.twig:
        autowire: true
        class: Vierwd\Symfony\Smarty\Extension\TwigInSmartyExtension

    smarty.extension.csrf:
        autowire: true
        class: Vierwd\Symfony\Smarty\Extension\CsrfExtension


    smarty.extension.modifier:
        autowire: true
        class: Vierwd\Symfony\Smarty\Extension\ModifierExtension

    smarty.image_service:
        autowire: true
        class: Vierwd\Symfony\Smarty\Service\ImageService

    smarty.service_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        autoconfigure: true
        arguments:
            -
                kernel: '@kernel'
                tagRenderer: '@webpack_encore.tag_renderer'
                imageService: '@smarty.image_service'
                extension.routing: '@smarty.extension.routing'
                extension.twig: '@smarty.extension.twig'
                extension.csrf: '@smarty.extension.csrf'
                extension.modifier: '@smarty.extension.modifier'
                twig.app_variable: '@twig.app_variable'

    smarty.engine.smarty:
        public: true
        autowire: true
        class: Vierwd\Symfony\Smarty\Templating\SmartyEngine
        arguments:
            $parser: '@smarty.name_parser'
            $loader: '@smarty.filesystem_loader'
            $locator: '@smarty.service_locator'
            $templateDirectories: [ '%smarty.template_path%' ]
            $pluginDirectories: [ '%smarty.plugin_path%' ]

    smarty.engine.php:
        class: Symfony\Component\Templating\PhpEngine
        arguments:
            $parser: '@smarty.name_parser'
            $loader: '@smarty.filesystem_loader'

    smarty.engine.twig:
        class: Vierwd\Symfony\Smarty\Templating\TwigEngine
        autowire: true
        arguments:
            $parser: '@smarty.name_parser'
            $loader: '@smarty.filesystem_loader'

    templating:
        public: true
        class: Symfony\Component\Templating\DelegatingEngine
        arguments:
            -
                - '@smarty.engine.smarty'
                - '@smarty.engine.twig'
                - '@smarty.engine.php'

    Vierwd\Symfony\Smarty\Templating\SmartyEngine:
      alias: smarty.engine.smarty

    Symfony\Component\Templating\DelegatingEngine:
        alias: templating
